### PR TITLE
R Support

### PR DESCRIPTION
**Pull request by jirikadlec2**
I have modified the dockerfile to install R, Rserve and R packages for WPS4R.

### CODE REVIEW

**Comment by swainn** [comment]
I built the Docker image and started it up successfully. R_Echo doesn't work. It gives me the error that the process identifier cannot be found. Back to the drawing board.

**Comment by jirikadlec2** [comment]
Here is what we should be getting if the docker is running correctly with R - there should be a checkbox next to the "Active" under LocalRAlgorithmRepository.
image

**Comment by jirikadlec2** [comment]
Attempt #2: I have added the missing command to supervisord.conf to start Rserve

**Comment by jirikadlec2** [comment]
Attempt #3: Modified the wps_config configuration file to enable the R-algorithms by default

**Pull request merged**
